### PR TITLE
Use `warc2zim2` branch of warc2zim.

### PR DESCRIPTION
**Pull request by mgautierfr**
Need #262 to be merged first.

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
LGTM

**Comment by benoit74** [comment]
@rgaudin could you please review again now that I've added the temporary Github workflow to build `zimit2` Docker image? Thanks

**Review by rgaudin — APPROVED** [review]
All good! You forced-pushed but the commits were small though 👍

**Comment by benoit74** [comment]
I had to force-push to update the base branch after the merge (and avoid strange Git history). And I did it before the review because the commits where quite obvious.

**Pull request merged**
